Minor changes
VyrodovMikhail/formal-lang-course pull request #3
Opened 2023-09-28 21:03 UTC by VyrodovMikhail

2023-09-29 17:53 UTC, EgorOrachyov requested changes

2023-09-29 17:53 UTC, EgorOrachyov commented on project/rpq_utils.py
> +    transitive_closure = nx.transitive_closure(intersection_graph, reflexive=True)
Такое ощущение что тут идет ненужная и тяжелая конвертация из автомата в networkx граф, который потом непонятно как замыкается транзитивно. Почему бы не убрать ненужную конвертацию, и не попробовать бы замыкать матрицу самостоятельно, тем более что матрицы после пересечения у вас есть, тк вы `kron` считаете?

2023-09-29 17:53 UTC, EgorOrachyov commented on project/automata_intersection.py
> +            result_automaton.add_transition(first_in_edge, label, second_in_edge)
сомнительное действие -- зачем делать матрицы, чтобы потом из них руками доставать элементы? это не эффективно

2023-09-29 17:53 UTC, EgorOrachyov commented on project/rpq_utils.py
> +import networkx as nx
Название файла можно просто `rpq`, слово utils тут не нужно

2023-10-03 17:26 UTC, EgorOrachyov requested changes

2023-10-03 17:26 UTC, EgorOrachyov commented on project/automata_intersection.py
> +        labels = [label] * len(rows_indexes)
Вы сделали матрицы и транзитивное замыкание честное, НО, зачем здесь получать все ребра, их будет очень много?

Дадее вы честно строите автомат с переходами, но для алгоритма это не требуется. Может все таки стоит сделать функцию пересечения, чтобы она пересекала ровно матрицы, без дополнительной ненужной работы?

2023-10-03 17:26 UTC, EgorOrachyov commented on project/rpq.py
> +    states_count, _ = random.choice(list(intersection_matricies.values())).shape
очень сомнительное решение, шейп можно и аргументом передать вкрайнем случае, или из 0ой матрицы взять

2023-10-03 17:26 UTC, EgorOrachyov commented on project/rpq.py
> +    (intersection_automaton, intersection_matrices) = intersect_automata(
вот тут автомат вы получли, но далее интересуют только стартовые и финальные, ЧЕСТНЫЙ автомат не нужен, поэтому я бы не возвращал автомат, а что-то свое, условно списки стартовых, финальны стейтов, матрицы, ТОЛЬКО то что вам требуется для алгоритма, минимизируя число ненужный вычислений

2023-10-03 19:41 UTC, VyrodovMikhail commented on project/rpq.py
> +    (intersection_automaton, intersection_matrices) = intersect_automata(
исправил. Я думал, что надо обязательно автомат возвращать, т.к. в задании написано реализовать функцию пересечения двух автоматов. Логично было подумать, что результатом этой функции должен быть тоже автомат. Ну да ладно.

2023-10-04 10:58 UTC, EgorOrachyov approved these changes

2023-10-04 11:00 UTC, merged